/**
 * Download format generators for the Faiceoff brand vault.
 *
 * Generates ZIP / PDF / DOCX packages from a vault image.
 * All functions return a Buffer suitable for streaming as a download response.
 *
 * External package versions (from package.json):
 *   jszip ^3.10.1
 *   @react-pdf/renderer ^4.5.1
 *   docx ^9.6.1
 */

import JSZip from 'jszip';
import {
  Document as PdfDocument,
  Page,
  View,
  Text,
  Image as PdfImage,
  renderToBuffer,
  StyleSheet,
} from '@react-pdf/renderer';
import {
  Document as DocxDocument,
  Packer,
  Paragraph,
  TextRun,
  ImageRun,
  HeadingLevel,
  AlignmentType,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
} from 'docx';
import { createElement } from 'react';
import type { GenerateDownloadInput } from './types';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Fetch a remote URL and return it as a Buffer.
 * Handles both http(s) URLs and data: URIs.
 */
async function fetchAsBuffer(url: string): Promise<{ buffer: Buffer; mimeType: string }> {
  if (url.startsWith('data:')) {
    const semi = url.indexOf(';');
    const comma = url.indexOf(',');
    const mimeType = url.slice(5, semi) || 'application/octet-stream';
    const buffer = Buffer.from(url.slice(comma + 1), 'base64');
    return { buffer, mimeType };
  }

  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch ${url}: HTTP ${response.status}`);
  }
  const arrayBuffer = await response.arrayBuffer();
  const mimeType = response.headers.get('content-type') ?? 'application/octet-stream';
  return { buffer: Buffer.from(arrayBuffer), mimeType };
}

/** Determine file extension from a URL or mime type. */
function imageExtension(url: string, mimeType?: string): string {
  // Try URL extension first
  const urlPath = url.split('?')[0];
  const ext = urlPath.split('.').pop()?.toLowerCase();
  if (ext && ['png', 'jpg', 'jpeg', 'webp', 'gif'].includes(ext)) return ext;

  // Fall back to MIME type
  const mimeMap: Record<string, string> = {
    'image/png': 'png',
    'image/jpeg': 'jpg',
    'image/webp': 'webp',
    'image/gif': 'gif',
  };
  return mimeMap[mimeType ?? ''] ?? 'png';
}

/** Attribution text for the readme included in ZIP packages. */
function buildReadmeText(generationId: string): string {
  return `Faiceoff — Licensed AI Likeness Image
======================================

Generation ID: ${generationId}
Generated by: Faiceoff (https://faiceoff.com)
Platform: Faiceoff AI Likeness Licensing Marketplace

License Summary
---------------
This image was generated using a creator's licensed likeness under the
Faiceoff Platform License Agreement. Use of this image is subject to
the terms agreed upon at the time of generation, including:

  • This image may only be used for the campaign specified in the
    generation brief.
  • Attribution to the creator and Faiceoff platform is required.
  • Commercial redistribution or sublicensing is prohibited without
    explicit written consent from the creator.
  • This license expires as defined in the associated license certificate.

For full license terms, refer to the enclosed license-cert.pdf (if present)
or visit https://faiceoff.com/legal/license-terms

Generated on: ${new Date().toUTCString()}
`;
}

// ---------------------------------------------------------------------------
// ZIP Package
// ---------------------------------------------------------------------------

/**
 * Generate a ZIP archive containing:
 *   - /image.{ext}       — the original generated image
 *   - /license-cert.pdf  — the license certificate (if certUrl provided)
 *   - /readme.txt        — attribution and license summary
 *
 * @returns A Buffer containing the ZIP file (magic bytes: PK\x03\x04)
 */
export async function generateOriginalZip(input: {
  imageUrl: string;
  certUrl?: string | null;
  generationId: string;
}): Promise<Buffer> {
  const { imageUrl, certUrl, generationId } = input;

  const zip = new JSZip();

  // Fetch and add the image
  const { buffer: imageBuffer, mimeType } = await fetchAsBuffer(imageUrl);
  const ext = imageExtension(imageUrl, mimeType);
  zip.file(`image.${ext}`, imageBuffer);

  // Fetch and add cert PDF if available
  if (certUrl) {
    try {
      const { buffer: certBuffer } = await fetchAsBuffer(certUrl);
      zip.file('license-cert.pdf', certBuffer);
    } catch (err) {
      // Cert fetch failure is non-fatal — log and continue without it
      console.warn(`[vault/zip] Failed to fetch cert for ${generationId}:`, err);
    }
  }

  // Add readme
  zip.file('readme.txt', buildReadmeText(generationId));

  const arrayBuffer = await zip.generateAsync({ type: 'arraybuffer' });
  return Buffer.from(arrayBuffer);
}

// ---------------------------------------------------------------------------
// PDF Package
// ---------------------------------------------------------------------------

const pdfStyles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#fdfbf7', // Paper color from design system
    padding: 0,
  },
  imagePage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#1a1513',
    padding: 0,
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'contain',
  },
  captionContainer: {
    position: 'absolute',
    bottom: 24,
    left: 0,
    right: 0,
    alignItems: 'center',
  },
  caption: {
    color: '#fdfbf7',
    fontSize: 10,
    fontFamily: 'Helvetica',
    opacity: 0.8,
  },
  certPage: {
    flex: 1,
    padding: 40,
    backgroundColor: '#fdfbf7',
  },
  heading: {
    fontSize: 20,
    fontFamily: 'Helvetica-Bold',
    color: '#1a1513',
    marginBottom: 8,
  },
  subheading: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: '#c9a96e', // Gold
    marginBottom: 16,
  },
  label: {
    fontSize: 9,
    fontFamily: 'Helvetica-Bold',
    color: '#1a1513',
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  value: {
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: '#1a1513',
    marginBottom: 10,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#c9a96e',
    marginVertical: 16,
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 40,
    right: 40,
    fontSize: 8,
    fontFamily: 'Helvetica',
    color: '#888',
    textAlign: 'center',
  },
});

/**
 * Generate a PDF package with:
 *   - Page 1: Image full-bleed with generation ID caption
 *   - Page 2: License details and brief metadata
 *
 * @returns A Buffer containing the PDF (magic bytes: %PDF)
 */
export async function generatePdfPackage(input: GenerateDownloadInput): Promise<Buffer> {
  const { imageUrl, generationId, brief = {} } = input;

  // Fetch image as base64 data URI for embedding
  const { buffer: imageBuffer, mimeType } = await fetchAsBuffer(imageUrl);
  const imageBase64 = `data:${mimeType};base64,${imageBuffer.toString('base64')}`;

  const briefEntries = Object.entries(brief).filter(
    ([k]) => !['pipeline_version', 'product_image_url'].includes(k),
  );

  const pdfDoc = createElement(
    PdfDocument,
    null,
    // Page 1: Image full-bleed
    createElement(
      Page,
      { size: 'A4', style: pdfStyles.imagePage },
      createElement(PdfImage, { src: imageBase64, style: pdfStyles.image }),
      createElement(
        View,
        { style: pdfStyles.captionContainer },
        createElement(
          Text,
          { style: pdfStyles.caption },
          `Faiceoff Generation ${generationId}`,
        ),
      ),
    ),
    // Page 2: License & brief
    createElement(
      Page,
      { size: 'A4', style: pdfStyles.certPage },
      createElement(Text, { style: pdfStyles.heading }, 'Faiceoff License Certificate'),
      createElement(Text, { style: pdfStyles.subheading }, 'AI Likeness Licensing Platform'),
      createElement(View, { style: pdfStyles.divider }),
      createElement(Text, { style: pdfStyles.label }, 'Generation ID'),
      createElement(Text, { style: pdfStyles.value }, generationId),
      createElement(Text, { style: pdfStyles.label }, 'Generated On'),
      createElement(Text, { style: pdfStyles.value }, new Date().toUTCString()),
      briefEntries.length > 0
        ? createElement(
            View,
            null,
            createElement(View, { style: pdfStyles.divider }),
            createElement(Text, { style: pdfStyles.subheading }, 'Generation Brief'),
            ...briefEntries.map(([key, value]) =>
              createElement(
                View,
                { key },
                createElement(Text, { style: pdfStyles.label }, key.replace(/_/g, ' ')),
                createElement(
                  Text,
                  { style: pdfStyles.value },
                  typeof value === 'string' ? value : JSON.stringify(value),
                ),
              ),
            ),
          )
        : null,
      createElement(View, { style: pdfStyles.divider }),
      createElement(Text, { style: pdfStyles.label }, 'License Terms'),
      createElement(
        Text,
        { style: pdfStyles.value },
        'This image is licensed for use under the Faiceoff Platform License Agreement. ' +
          'Use is restricted to the specified campaign. Commercial redistribution is prohibited ' +
          'without explicit written consent from the creator.',
      ),
      createElement(
        Text,
        { style: pdfStyles.footer },
        `© ${new Date().getFullYear()} Faiceoff — faiceoff.com`,
      ),
    ),
  );

  return renderToBuffer(pdfDoc);
}

// ---------------------------------------------------------------------------
// DOCX Package
// ---------------------------------------------------------------------------

/**
 * Generate a DOCX package with:
 *   - Title and brand info
 *   - Embedded image (as Base64 ImageRun)
 *   - Generation brief details
 *   - License terms text
 *
 * @returns A Buffer containing the DOCX (ZIP-based; magic bytes: PK\x03\x04 with [Content_Types].xml)
 */
export async function generateDocxPackage(input: GenerateDownloadInput): Promise<Buffer> {
  const { imageUrl, generationId, brief = {}, creator, brand } = input;

  // Fetch image for embedding
  const { buffer: imageBuffer, mimeType } = await fetchAsBuffer(imageUrl);

  // Determine image type for docx ImageRun
  const extToType = {
    png: 'png',
    jpg: 'jpg',
    jpeg: 'jpg',
    webp: 'png', // docx doesn't support webp, convert header — rasterized content should still show
    gif: 'gif',
  } as const;
  const ext = imageExtension(imageUrl, mimeType);
  const imageType = extToType[ext as keyof typeof extToType] ?? 'png';

  const briefEntries = Object.entries(brief).filter(
    ([k]) => !['pipeline_version', 'product_image_url'].includes(k),
  );

  const noBorder = {
    top: { style: BorderStyle.NONE, size: 0 },
    bottom: { style: BorderStyle.NONE, size: 0 },
    left: { style: BorderStyle.NONE, size: 0 },
    right: { style: BorderStyle.NONE, size: 0 },
    insideHorizontal: { style: BorderStyle.NONE, size: 0 },
    insideVertical: { style: BorderStyle.NONE, size: 0 },
  };

  const doc = new DocxDocument({
    sections: [
      {
        properties: {},
        children: [
          // Title
          new Paragraph({
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: 'Faiceoff — Licensed AI Image',
                bold: true,
                size: 48,
                color: '1a1513',
              }),
            ],
          }),

          // Subtitle
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: 200, after: 400 },
            children: [
              new TextRun({
                text: 'AI Likeness Licensing Platform',
                size: 24,
                color: 'c9a96e',
              }),
            ],
          }),

          // Metadata table
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            borders: noBorder,
            rows: [
              new TableRow({
                children: [
                  new TableCell({
                    borders: noBorder,
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: 'Generation ID', bold: true })],
                      }),
                    ],
                    width: { size: 30, type: WidthType.PERCENTAGE },
                  }),
                  new TableCell({
                    borders: noBorder,
                    children: [new Paragraph({ children: [new TextRun({ text: generationId })] })],
                  }),
                ],
              }),
              ...(creator
                ? [
                    new TableRow({
                      children: [
                        new TableCell({
                          borders: noBorder,
                          children: [
                            new Paragraph({
                              children: [new TextRun({ text: 'Creator', bold: true })],
                            }),
                          ],
                          width: { size: 30, type: WidthType.PERCENTAGE },
                        }),
                        new TableCell({
                          borders: noBorder,
                          children: [
                            new Paragraph({
                              children: [
                                new TextRun({
                                  text: creator.display_name,
                                }),
                              ],
                            }),
                          ],
                        }),
                      ],
                    }),
                  ]
                : []),
              ...(brand
                ? [
                    new TableRow({
                      children: [
                        new TableCell({
                          borders: noBorder,
                          children: [
                            new Paragraph({
                              children: [new TextRun({ text: 'Brand', bold: true })],
                            }),
                          ],
                          width: { size: 30, type: WidthType.PERCENTAGE },
                        }),
                        new TableCell({
                          borders: noBorder,
                          children: [
                            new Paragraph({
                              children: [new TextRun({ text: brand.company_name })],
                            }),
                          ],
                        }),
                      ],
                    }),
                  ]
                : []),
              new TableRow({
                children: [
                  new TableCell({
                    borders: noBorder,
                    children: [
                      new Paragraph({ children: [new TextRun({ text: 'Date', bold: true })] }),
                    ],
                    width: { size: 30, type: WidthType.PERCENTAGE },
                  }),
                  new TableCell({
                    borders: noBorder,
                    children: [
                      new Paragraph({
                        children: [new TextRun({ text: new Date().toUTCString() })],
                      }),
                    ],
                  }),
                ],
              }),
            ],
          }),

          // Spacer
          new Paragraph({ spacing: { before: 400 } }),

          // Image section heading
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: 'Generated Image', bold: true, color: '1a1513' })],
            spacing: { before: 400, after: 200 },
          }),

          // Embedded image
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new ImageRun({
                data: imageBuffer,
                transformation: { width: 480, height: 480 },
                type: imageType as 'png' | 'jpg' | 'gif',
              }),
            ],
          }),

          // Brief section
          ...(briefEntries.length > 0
            ? [
                new Paragraph({
                  heading: HeadingLevel.HEADING_1,
                  children: [
                    new TextRun({ text: 'Generation Brief', bold: true, color: '1a1513' }),
                  ],
                  spacing: { before: 400, after: 200 },
                }),
                new Table({
                  width: { size: 100, type: WidthType.PERCENTAGE },
                  borders: noBorder,
                  rows: briefEntries.map(
                    ([key, value]) =>
                      new TableRow({
                        children: [
                          new TableCell({
                            borders: noBorder,
                            children: [
                              new Paragraph({
                                children: [
                                  new TextRun({
                                    text: key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
                                    bold: true,
                                  }),
                                ],
                              }),
                            ],
                            width: { size: 30, type: WidthType.PERCENTAGE },
                          }),
                          new TableCell({
                            borders: noBorder,
                            children: [
                              new Paragraph({
                                children: [
                                  new TextRun({
                                    text: typeof value === 'string' ? value : JSON.stringify(value),
                                  }),
                                ],
                              }),
                            ],
                          }),
                        ],
                      }),
                  ),
                }),
              ]
            : []),

          // License terms
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            children: [new TextRun({ text: 'License Terms', bold: true, color: '1a1513' })],
            spacing: { before: 400, after: 200 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text:
                  'This image was generated under the Faiceoff Platform License Agreement. ' +
                  'Use is restricted to the campaign for which this generation was created. ' +
                  'Commercial redistribution, sublicensing, or use outside the agreed scope ' +
                  'is prohibited without explicit written consent from the creator. ' +
                  'Full terms are available at faiceoff.com/legal/license-terms.',
              }),
            ],
          }),

          // Footer
          new Paragraph({
            alignment: AlignmentType.CENTER,
            spacing: { before: 600 },
            children: [
              new TextRun({
                text: `© ${new Date().getFullYear()} Faiceoff — faiceoff.com`,
                color: '888888',
                size: 16,
              }),
            ],
          }),
        ],
      },
    ],
  });

  const arrayBuffer = await Packer.toBuffer(doc);
  return Buffer.from(arrayBuffer);
}
